
/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JayStorm Admin http://JayData.org for more info        /////////
//////                             oData V2                                    /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function (global, $data, undefined) {

    $data.Entity.extend('flowershopdb.Category', {
        'id': { 'key': true, 'nullable': false, 'computed': true, 'type': 'Edm.String' },
        'Name': { 'maxLength': 200, 'nullable': true, 'type': 'Edm.String' },
        'CategoryName': { 'maxLength': 200, 'nullable': true, 'type': 'Edm.String' },
        'Description': { 'nullable': true, 'type': 'Edm.String' },
        'ImageUrl': { 'maxLength': 200, 'nullable': true, 'type': 'Edm.String' }        
    });

    $data.Entity.extend('flowershopdb.Customer', {
        'id': { 'key': true, 'nullable': false, 'computed': true, 'type': 'Edm.String' },
        'Name': { 'maxLength': 200, 'nullable': true, 'type': 'Edm.String' },
        'Address': { 'maxLength': 200, 'nullable': true, 'type': 'Edm.String' }
    });

    $data.Entity.extend('flowershopdb.OrderItem', {
        'id': { 'key': true, 'nullable': false, 'computed': true, 'type': 'Edm.String' },
        'Product_ID': { 'nullable': false, 'required': true, 'type': 'Edm.String' },
        'Amount': { 'nullable': false, 'required': true, 'type': 'Edm.Double' },
        'Order_ID': { 'nullable': false, 'required': true, 'type': 'Edm.String' }
    });

    $data.Entity.extend('flowershopdb.Order', {
        'id': { 'key': true, 'nullable': false, 'computed': true, 'type': 'Edm.String' },
        'OrderDate': { 'nullable': true, 'type': 'Edm.DateTime' },
        'Customer_ID': { 'nullable': true, 'type': 'Edm.String' },
        'OrderState': { 'nullable': true, 'type': 'Edm.Int32' }
    });

    $data.Entity.extend('flowershopdb.Flower', {
        'id': { 'key': true, 'nullable': false, 'computed': true, 'type': 'Edm.String' },
        'Name': { 'maxLength': 200, 'nullable': true, 'type': 'Edm.String' },
        'Price': { 'nullable': false, 'required': true, 'type': 'Edm.Double' },
        'ImageUrl': { 'nullable': true, 'type': 'Edm.String' },
        'Category_ID': { 'nullable': true, 'type': 'Edm.String' },
        'Description': { 'nullable': true, 'type': 'Edm.String' }
    });

    $data.EntityContext.extend('flowershopdb.flowershopdbService', {
        'Categories': { type: $data.EntitySet, elementType: flowershopdb.Category },
        'Customers': { type: $data.EntitySet, elementType: flowershopdb.Customer },
        'OrderItems': { type: $data.EntitySet, elementType: flowershopdb.OrderItem },
        'Orders': { type: $data.EntitySet, elementType: flowershopdb.Order },
        'Flowers': { type: $data.EntitySet, elementType: flowershopdb.Flower }
    });

    $data.generatedContexts = $data.generatedContexts || [];
    $data.generatedContexts.push(flowershopdb.flowershopdbService);

    /*Context Instance*/
    context = new flowershopdb.flowershopdbService({ name: 'oData', oDataServiceHost: 'https://7a13bb7f-fd50-4f81-ab48-6369e0feee6f.jaystack.net/flowershopdb' });


})(window, $data);

